# Generated by Django 4.2.1 on 2023-07-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_signupqueue_v_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupqueue',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
