# Generated by Django 4.2.1 on 2023-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_signupqueue_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupqueue',
            name='v_code',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
